### ISSUE TITLE
I can't install anbox on meizu pro5 16.04 dev

### ISSUE THREAD

**Issue by Billdemoncho** [ubports/anbox#19]
Hello. Hello. 
On a Meizu pro5 in 16.04 dev
I'm trying to install anbox according to the tutorial:
https://docs.ubports.com/fr/latest/userguide/dailyuse/anbox.html?highlight=anbox
But I have errors when loading and therefore I can't install it.
see below: 

Could someone help me?
![capture du 2018-10-07 11-07-52](https://user-images.githubusercontent.com/42817545/46580669-7d551d00-ca29-11e8-9254-27545dac75ac.png)

**Comment by ghost** [comment]
Hi, 
That's old instructions !

Your need to follow this:

Flash kernel for your Pro 5 device
----------------------------------
adb shell 
sudo reboot -f bootloader
wget http://cdimage.ubports.com/anbox-images/anbox-boot-turbo-test.img
sudo fastboot flash bootimg anbox-boot-turbo-test.img
sudo fastboot reboot
rm anbox-boot-turbo-test.img


Install Anbox on your Pro 5 device
----------------------------------
adb shell 
sudo mount -o rw,remount /
sudo apt update
sudo apt install anbox-ubuntu-touch
anbox-tool install


Install apps on Anbox
---------------------
adb shell 
sudo mount -o rw,remount /
sudo apt update
sudo apt install android-tools-adb
adb install my-app.apk

**Comment by Billdemoncho** [comment]
Thanks Xray1970
I just installed anbox, and some basic applications have appeared in the dock.
Almost all of them do not work on my Meizu Pro 5.
The only one that works is the "Morph Browser" application that opens a window for me but not at the size of my screen and with a font too large.
In addition, she has taken the place of Bowser Next who has disappeared and I can no longer find my favourites.
Are there any configuration solutions?
Tell me too how I can delete the application. I just removed the package with:

sudo apt purge -f anbox-ubuntu-touch

but after rebooting the anbox apps are still there, how do we delete all that?
I'll probably come back to it a little later....

Translated with www.DeepL.com/Translator

**Comment by ghost** [comment]
Hi,

I dont know how to remove complete Anbox, we need to wait when Marius will reply for that sorry.

I just found this of Marius reply on Telegram try that: sudo apt remove anbox anbox-common

**Comment by Billdemoncho** [comment]
Thank you but apparently everything is still there...

**Comment by ghost** [comment]
Ok then we need to wait for Marius...

**Comment by Billdemoncho** [comment]
Hello, 

Could Marius explain to me how to uninstall the application?

Maybe, the cause is this error?
"W: No sandbox user "_apt' on the system, can not drop privileges"

a big thank you for the progress of your work.

**Comment by Billdemoncho** [comment]
I reset the device while waiting for a solution.
