### ISSUE TITLE
Yalp store app crashes

### ISSUE THREAD

**Issue by YugiFanGX** [ubports/anbox#21]
The open source application Yalp (which lets you download Google Play apps) crashes

**Comment by TartanSpartan** [comment]
This can be fixed by ensuring you spoof your phone to a different device in the app settings (for me switching to the Fairphone 2 on an MX4 device worked).

**Comment by YugiFanGX** [comment]
where can I find these options?

**Comment by ghost** [comment]
Into the lasted version you can found that when you login with your account.
