### ISSUE TITLE
Add on-screen keyboard

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/anbox#3]
**Please describe your problem:**
There's no on-screen keyboard

**What were you expecting?:**
On-screen keyboard so that you can type things into android apps.

**Additional info:**

**Comment by mariogrip** [comment]
Fixed by adding hack to allow android keyboard, this is temporarily solution. Added bug report to add support for native keyboard here: https://github.com/ubports/anbox/issues/5


**Upgrade using:**
note, Using apt install here, that way we upgrade just anbox and nothing else
```
sudo mount -o rw,remount /
sudo apt update
sudo apt install anbox anbox-common anbox-ubuntu-touch
anbox-tool upgrade
```
