### ISSUE TITLE
Anbox apps not working

### ISSUE THREAD

**Issue by aclifton314** [ubports/anbox#37]
**SYSTEM**
 - Oneplus One (bacon)
 - OTA-11 16.04

Hi Everyone,

I was able to successfully install anbox on my Oneplus One (Ubuntu 16.04). I was also able to pull apk's from my android device and push them to my ubuntu-touch device. I tried the following two methods of installation:

* `adb install my_app.apk`
* 
```
 sudo mv my_app.apk ~/anbox-data/data
$ sudo lxc-console -ndefault -P /home/phablet/anbox-data/containers -t0
$ cd ../data && pm install my_app.apk
```

Both methods successfully install my_app.apk and it shows up in the app scope once I refresh it (with a swipe down). However, when I launch the newly installed apps, they just hang on the opening. For instance, spotify just shows the spotify logo. Hopper just shows a white background.

Perhaps these were not installed successfully, but from the instructions I could find, these were the recommended ways. I'm aware that anbox is extremely experimental at this point so perhaps these apps just don't work. In that case, has anyone been able to successfully install and deploy an android app on a OPO? If so which one?

I was curious to know, in addition to the above, if there were another way to install android apps in anbox? Thanks in advance.

**Comment by Flohack74** [comment]
The big question here is, do these Apps require GApps installed, or depend on other APIs that are not there in Anbox? You need to remember, Anbox is by no way a complete ecosystem now. First of all, you cannot install GApps there, so probably all kind of Apps will break that need Google Mapps, or other features. Also all kind of hardware access like camera, sound sensors is not possible at the moment.
Do the simple Apps work that are preinstalled, like the calculator?

**Comment by aclifton314** [comment]
@Flohack74 I checked the preinstalled settings app and calculator app and they seem to work.

**Comment by Flohack74** [comment]
Yeah so I assume the other Apps have dependencies on GApps and stuff thats not in Anbox. Thats the sad part about it - we cannot tell if this situation will ever improve. Currently Anbox is (and will be for a longer time) strictly experimental. Its not a launch product, for good reasons.

**Comment by aclifton314** [comment]
@Flohack74 would it be the case that spotify has GApps dependencies if I can't get it to run on my OPO but someone else got it to work on their Fairphone2? In other words, is it fair to say that if someone got spotify running on an UT flashed Fairphone2 that it should also work on a UT flashed OPO?

**Comment by Flohack74** [comment]
No idea but basically yes. Anbox is a container, it is device-agnostic, given the fact that you need the right kernel installed.

**Comment by aclifton314** [comment]
@Flohack74 Ok, that makes sense. I'll mess around with it this weekend and close the issue for now. As I imagine other people might be interested, if I find anything useful I'll post it here. Thanks for your help!
