### ISSUE TITLE
No network

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/anbox#4]
In system settings, it only let's me view more, than Airplane mode, VPN, and Network settings reset.

Rather than letting me connect and use my WiFi.

**Comment by mariogrip** [comment]
It should use your host (ubuntu touch) network, no need to set that in android itself. Think of anbox more like a virtual box.

**Comment by PhoenixLandPirate** [comment]
Apitiode complains that it cant connect to the internet and f-droid doesnt refresh so it doesnt update, so it's not working on mine

**Comment by mariogrip** [comment]
I have now updated the image with an version that has working network! You can update this using `anbox-tool upgrade`

**Comment by tomoqv** [comment]
It seems that some Android apps are able to use the host internet connection, while some are not.
