### ISSUE TITLE
Anbox Oneplus One

### ISSUE THREAD

**Issue by LennardUT** [ubports/anbox#44]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by LennardUT** [comment]
After command sudo reboot -f bootlader my device will start fastboot but will stuck at seeing the logo fastboot. My device disconnect and i could only reboot manually my device and have to start again at the beginning. What am i doing wrong? Could i also replace and start the image with ssh?

**Comment by Flohack74** [comment]
Anbox is deprecated and will not be developed further. Please start using Waydroid.
