### ISSUE TITLE
Anbox freeze all system and reboot device

### ISSUE THREAD

**Issue by CDLProduction** [ubports/anbox#45]
**Please describe your problem:**
I run anbox on UT device lavender dev build. I try to install yandex music app and just after few moments phone is freezing and reboot the graphical environment.

**What were you expecting?:**
Anbox work well and not freeze all system, if problem appear it just crash the app not entire system.

**Comment by Flohack74** [comment]
Anbox is a developer preview, there is nothing we can do to make it compatible for all Android apps right now. I will close this, as we are trying a new approach for Anbox with a later Android version. Please retry as soon as this is released.
