### ISSUE TITLE
bq Aquaris M10 FHD - Anbox has not been enabled for this Device

### ISSUE THREAD

**Issue by BeLeFu** [ubports/anbox#48]
I followed the instructions [here](https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html), flashed the frieza kernel to the device and when I ran the `anbox-tool install` command it printed out

`Anbox has not been enabled for this device. Please consult device maintainer.` 

Retried multiple times and it always did the same. What am I doing wrong?

**Comment by droid001** [comment]
Someone had the same issue [in the forums](https://forums.ubports.com/topic/6162/anbox-not-working-ota-17). Seems like our M10 FHD devices aren't supported any longer.

**Comment by danield5732** [comment]
I can confirm the issue with same device.
However, [https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html](url) should be updated in this case?

**Comment by Flohack74** [comment]
Anbox is deprecated and will no longer be supported. Unfortunately the follow-up technology "Waydroid" will not run no such older devices but is targeted for devices that came with Android 9 or later.
