### ISSUE TITLE
Invalid APK file

### ISSUE THREAD

**Issue by amostol** [ubports/anbox#50]
I keep getting a error message, it says "Invalid APK file". I have tried multiple files and always get the same message. I have tried using the whole file name as it shows up in my downloads folder. The one file had () in it, then it would give a syntax error. Which is confusing as that is in the name. Is there a special format that the name needs to be in? or does the file need to be extracted first? 

Here are the full file names I've tried 
com.waze_4.80.60.601-1022751_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk.download
Waze GPS Maps Traffic Alerts Live Navigation_v4.80.0.1_apkpure.com.apk

I'm using a Volla Phone, I know it is not on the list of compatible phones, but anbox seems to have installed correctly.

**Comment by Flohack74** [comment]
Anbox is deprecated and will not be developed further. Please start using Waydroid.
